Metrics/BlockLength:
  Exclude:
    - hcheck.gemspec
    - 'spec/hcheck/**/*.rb'
Metrics/MethodLength:
  Max: 16
Metrics/LineLength:
  Max: 110
  Exclude:
    - hcheck.gemspec
    - 'spec/hcheck/**/*.rb'
Lint/AssignmentInCondition:
  Enabled: false
