Metrics/BlockLength:
  Exclude:
    - hcheck.gemspec
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 16
Metrics/LineLength:
  Max: 110
  Exclude:
    - hcheck.gemspec
    - 'spec/**/*.rb'
Lint/AssignmentInCondition:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
Style/FrozenStringLiteralComment:
  Enabled: false
