Metrics/BlockLength:
  Exclude:
    - hcheck.gemspec
    - 'spec/hcheck/**/*.rb'
Metrics/LineLength:
  Exclude:
    - hcheck.gemspec
    - 'spec/hcheck/**/*.rb'
Lint/AssignmentInCondition:
  Enabled: false
